clock/config/routes.rb
Rails.application.routes.draw do
  root 'main#index'
  resources :reports
  resources :stores
  resources :employees
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

clock/app/views/shared/_sidebar.html.erb
<div class="col-3">
  <ul class="nav nav-tabs flex-column" id="navTabs">
    <div class="sb-sidenav-menu-heading">Reports</div>
    <li class="nav-item">
      <%= link_to 'Attendance', reports_path, class: "nav-link" %>
    </li>
    <li class="nav-item">
      <a aria-controls="second-pane" class="nav-link" id="second-tab">Absence</a>
    </li>
    <li class="nav-item"><hr></li>
    <div class="sb-sidenav-menu-heading">Employees</div>
    <li class="nav-item">
      <%= link_to 'Show', employees_path, class: "nav-link" %>
    </li>
    <li class="nav-item">
      <%= link_to 'Create', new_employee_path, class: "nav-link" %>
    </li>
    <li class="nav-item"><hr></li>
    <div class="sb-sidenav-menu-heading">Stores</div>
    <li class="nav-item">
      <%= link_to 'Show', stores_path, class: "nav-link" %>
    </li>
    <li class="nav-item">
      <%= link_to 'Create', new_store_path , class: 'nav-link'%>
    </li>
    <li class="nav-item"><hr></li>
    <li>
      <% if signed_in? %>
        <div class="sb-sidenav-menu-heading">Signed in as: <br>
        <%= current_user.email %></div>
        <%= link_to 'Sign out', sign_out_path, method: :delete, class: 'nav-link' %>
      <% else %>
        <%= link_to 'Sign in', sign_in_path, class: 'nav-link' %>
      <% end %>
    </li>
  </ul>
</div>