clock/config/routes.rb
Rails.application.routes.draw do
  root 'main#index'
  resources :reports
  resources :stores
  resources :employees
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

clock/app/models/report.rb
class Report < ApplicationRecord
  belongs_to :employee
end

clock/app/controllers/reports_controller.rb
# frozen_string_literal: true

# ReportsController
class ReportsController < ApplicationController
  before_action :require_login, except: %i[new create edit update]
  before_action :set_report, only: %i[show edit update destroy]

  # GET /reports
  # GET /reports.json
  def index
    @reports = Report.all
  end

  # GET /reports/1
  # GET /reports/1.json
  def show; end

  # GET /reports/new
  def new
    @employee = Employee.find_by(nip: params['employee']&.[]('nip'))
    @pending_report = @employee.reports.find_by(hour_finish: nil) if @employee.present?

    redirect_to edit_report_path(@pending_report) if @pending_report.present?

    @report = Report.new
  end

  # GET /reports/1/edit
  def edit
    @employee = @report.employee
  end

  # POST /reports
  # POST /reports.json
  def create
    employee = Employee.find(report_params[:employee_id])
    @report = Report.new(employee: employee, date: Date.today, hour_start: Time.now, hour_finish: nil, work_day: Date.today.strftime('%A'))

    respond_to do |format|
      if @report.save
        format.html { redirect_to new_report_url, notice: 'Report was successfully updated.' }
        format.json { render :show, status: :ok, location: @report }
      else
        format.html { render :new }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /reports/1
  # PATCH/PUT /reports/1.json
  def update
    respond_to do |format|
      if @report.update(hour_finish: Time.now)
        format.html { redirect_to new_report_url, notice: 'Report was successfully updated.' }
        format.json { render :show, status: :ok, location: @report }
      else
        format.html { render :edit }
        format.json { render json: @report.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /reports/1
  # DELETE /reports/1.json
  def destroy
    @report.destroy
    respond_to do |format|
      format.html { redirect_to reports_url, notice: 'Report was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_report
    @report = Report.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def report_params
    params.require(:report).permit(:employee_id, :date, :hour_start, :hour_finish, :work_day)
  end

  def employee_params
    params.require(:employee).permit(:nip)
  end
end

clock/app/views/reports/_form.html.erb
<% if report.errors.any? %>
  <div class="alert alert-danger alert-dismissible" id="store-errors">
    <button type="button" class="close">&times;</button>
    <div id="error_explanation">
      <h2><%= pluralize(report.errors.count, "error") %> prohibited this report from being saved:</h2>
      <ul>
        <% report.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>

<%= form_with(url: new_report_path, method: :get, local: true) do |form| %>
  <div class="form-group">
    <%= form.label :employee_nip %>
    <%= password_field(:employee, :nip, value: @employee&.nip) %>
  </div>

  <div class="form-group">
    <%= form.submit "Search", class: 'btn btn-primary float-center' %>
  </div>
<% end %>

<%- if @employee.present? %>
  <%= form_with model: @report, remote: true do |form| %>
    <div class="form-group">
      <%= form.hidden_field :employee_id, value: @employee.id %>
    </div>

    <div class="form-group">
      <%= form.submit "#{ @report.new_record? ? "Check in" : "Check out" }", class: 'btn btn-secondary float-center' %>
    </div>
  <% end %>
<% end %>

clock/app/views/reports/edit.html.erb
<h1 class="d-flex justify-content-center">Enter your secret number:</h1>
<div class="d-flex justify-content-center">
  <%= render 'form', report: @report %>
</div>

clock/app/views/reports/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Reports</h1>

<table class="table">
  <thead>
    <tr>
      <th scope="col">Employee</th>
      <th scope="col">Date</th>
      <th scope="col">Hour start</th>
      <th scope="col">Hour finish</th>
      <th scope="col">Work day</th>
      <th colspan="3" scope="col"></th>
    </tr>
  </thead>

  <tbody>
    <% @reports.each do |report| %>
      <tr>
        <td scope="row"><%= Employee.find(report.employee_id).name %></td>
        <td><%= report.date %></td>
        <td><%= report.hour_start.strftime("%I:%M %p")  %></td>
        <td><%= report.hour_finish.strftime("%I:%M %p") unless report.hour_finish.nil? %></td>
        <td><%= report.work_day %></td>
        <td><%= link_to 'Show', report %></td>
        <td><%= link_to 'Edit', edit_report_path(report) %></td>
        <td><%= link_to 'Destroy', report, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Report', new_report_path %>

clock/app/views/reports/new.html.erb
<h1 class="d-flex justify-content-center">Enter your secret number:</h1>
<div class="d-flex justify-content-center">
  <%= render 'form', report: @report %>
</div>

clock/app/views/reports/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Employee:</strong>
  <%= @report.employee_id %>
</p>

<p>
  <strong>Date:</strong>
  <%= @report.date %>
</p>

<p>
  <strong>Hour start:</strong>
  <%= @report.hour_start %>
</p>

<p>
  <strong>Hour finish:</strong>
  <%= @report.hour_finish %>
</p>

<p>
  <strong>Work day:</strong>
  <%= @report.work_day %>
</p>

<%= link_to 'Edit', edit_report_path(@report) %> |
<%= link_to 'Back', reports_path %>