clock/config/routes.rb
Rails.application.routes.draw do
  root 'main#index'
  resources :reports
  resources :stores
  resources :employees
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

clock/app/models/store.rb
class Store < ApplicationRecord
  validates :name, presence: true, format: { with: /([a-zA-ZàáâäãåąčćęèéêëėįìíîïłńòóôöõøùúûüųūÿýżźñçčšžÀÁÂÄÃÅĄĆČĖĘÈÉÊËÌÍÎÏĮŁŃÒÓÔÖÕØÙÚÛÜŲŪŸÝŻŹÑßÇŒÆČŠŽ∂ð ,.'-]{2,48})/i }
  validates :phone, presence: true, length: { minimum: 7 }, format: { with: /([+()0-9])\w+/i, message: "You can only use numbers, parentheses and + sign"}
  validates :address, presence: true, format: { with: /([a-zA-Z0-9#])\w+/i, message: "You can only use letters, numbers and the # sign"}
end

clock/app/controllers/stores_controller.rb
# frozen_string_literal: true

# Store Controller
class StoresController < ApplicationController
  before_action :require_login
  before_action :set_store, only: %i[show edit update destroy]

  # GET /stores
  # GET /stores.json
  def index
    @stores = Store.where(status: true)
  end

  # GET /stores/1
  # GET /stores/1.json
  def show; end

  # GET /stores/new
  def new
    @store = Store.new
  end

  # GET /stores/1/edit
  def edit
    @show_btn = true
  end

  # POST /stores
  # POST /stores.json
  def create
    @store = Store.new(store_params)

    respond_to do |format|
      if @store.save
        format.html { redirect_to @store, notice: 'Store was successfully created.' }
        format.json { render :show, status: :created, location: @store }
      else
        format.html { render :new }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stores/1
  # PATCH/PUT /stores/1.json
  def update
    respond_to do |format|
      if @store.update(store_params)
        format.html { redirect_to @store, notice: 'Store was successfully updated.' }
        format.json { render :show, status: :ok, location: @store }
      else
        format.html { render :edit }
        format.json { render json: @store.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stores/1
  # DELETE /stores/1.json
  def destroy
    @store = Store.find(params[:id])
    if @store.status
      @store.update(status: false)
      flash[:notice] = "Successfully disabled #{@store.name}."
      flash[:notice] = "Failed to disable #{@store.name}."
      render action: :show
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_store
    @store = Store.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def store_params
    params.require(:store).permit(:name, :address, :phone, :open_time, :close_time, :status)
  end
end

clock/app/views/stores/_form.html.erb
<% if store.errors.any? %>
  <div class="alert alert-danger alert-dismissible" id="store-errors">
    <button type="button" class="close">&times;</button>
    <strong>Danger!</strong> 
    <div id="error_explanation">
      <h2><%= pluralize(store.errors.count, "error") %> prohibited this store from being saved:</h2>
      <ul>
        <% store.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  </div>
<% end %>

<div class="container">
  <div class="row">
    <div class="col-sm-2">
      <div class="row">
        <div class="col-sm-12">
        <img src="https://picsum.photos/200/200" class="img-thumbnail" />
        </div>
        <div class="col-sm-12">
        <!-- segmento para el mapa--> 
        </div>
      </div>
    </div>
    <div class="col-sm-10">
      <%= form_with(model: store, local: true, class: "form-horizontal") do |form| %>

        <div class="form-group row">
          <%= form.label :id, class: "col-sm-2 col-form-label" %>
          <div class="col-sm-10">
            <%= form.text_field :id, placeholder: "Store Number", class: "form-control", disabled: true %>
          </div>
        </div>

        <%= form.hidden_field :status, value: true %>

        <div class="form-group row">
          <%= form.label :name, class: "col-sm-2 col-form-label" %>
          <div class="col-sm-10">
            <%= form.text_field :name, placeholder: "Store Name", class: "form-control" %>
          </div>
        </div>

        <div class="form-group row">
          <%= form.label :phone, class: "col-sm-2 col-form-label" %>
          <div class="col-sm-10">
            <%= form.text_field :phone, placeholder: "+52 (312) 000 0000", class: "form-control" %>
          </div>
        </div>

        <div class="form-group row">
          <%= form.label :address, class: "col-sm-2 col-form-label" %>
          <div class="col-sm-10">
            <%= form.text_field :address, placeholder: "Address Name # 101, Colima", class: "form-control" %>
          </div>
        </div>

        <div class="form-group row">
          <%= form.label :open_time, class:  "col-sm-2 col-form-label" %>
          <div class="col-sm-10">
            <%= form.time_select :open_time, class: "form-control" %>
          </div>
        </div>

        <div class="form-group row">
          <%= form.label :close_time, class: "col-sm-2 col-form-label" %>
          <div class="col-sm-10">
            <%= form.time_select :close_time, class: "form-control" %>
          </div>
        </div>

        <div class="form-group row">
          <div class="col-sm-10 offset-sm-2">
            <% if @show_btn %> 
              <%= link_to 'Delete', @store, method: :delete, data: { confirm: 'Do you want to delete the store?' }, class: 'btn btn-danger float-right' %>
            <% end %>
            <%= form.submit class: 'btn btn-primary float-right', data: { confirm: 'Do you want to confirm this action?' } %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

clock/app/views/stores/edit.html.erb
<h1>Editing Store</h1>

<%= render 'form', store: @store %>

<%= link_to 'Show', @store %> |
<%= link_to 'Back', stores_path %>

clock/app/views/stores/index.html.erb
<div class="container">
  <div class="row">
      <% @stores.each do |store| %>
        <div class="col-md-4">
          <div class="card mb-4 shadow-sm">
          <img src="https://picsum.photos/200/200" class="img-thumbnail" />
            <div class="card-body">
              <p class="card-text">
                <p><strong>Name:</strong> <%= store.name %></p>
                <p><strong>Store number:</strong> <%= store.id %></p>
              </p>
              <div class="d-flex justify-content-between align-items-center">
                <%= link_to 'Show', edit_store_path(store), class: 'btn btn-primary btn-lg btn-block' %>
              </div>
            </div>
          </div>
        </div>
      <% end %>
  </div>
</div>

clock/app/views/stores/new.html.erb
<h1>New Store</h1>

<%= render 'form', store: @store %>

<%= link_to 'Back', stores_path %>

clock/app/views/stores/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @store.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @store.address %>
</p>

<p>
  <strong>Phone:</strong>
  <%= @store.phone %>
</p>

<p>
  <strong>Open time:</strong>
  <%= @store.open_time %>
</p>

<p>
  <strong>Close time:</strong>
  <%= @store.close_time %>
</p>

<p>
  <strong>Status:</strong>
  <%= @store.status %>
</p>

<%= link_to 'Edit', edit_store_path(@store) %> |
<%= link_to 'Back', stores_path %>