clock/config/routes.rb
Rails.application.routes.draw do
  root 'main#index'
  resources :reports
  resources :stores
  resources :employees
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

clock/app/models/employee.rb
class Employee < ApplicationRecord
  has_many :reports
  serialize :work_days
  validates :name, presence: true, length: { minimum:1 }, format: { with: /([A-Za-z áéíóúÁÉÍÓÚ]{2,48})\w+/i }
  validates :nip, presence: true, format: { with: /([0-9])\w+/i }
  validates :address, presence: true, format: { with: /([a-zA-Z0-9# ])\w+/i }
  validates :phone, presence: true, length: { minimum: 7 }, format: { with: /([+()0-9])\w+/i, message: "You can only use numbers, parentheses and + sign"}
  validates :work_days, presence: true
  validates_each :work_days do |record, attr, value|
    record.errors.add attr, 'Must have at least one checked' if value.length < 1
  end
end

clock/app/controllers/employees_controller.rb
# frozen_string_literal: true

# Employee Controller
class EmployeesController < ApplicationController
  before_action :require_login
  before_action :set_employee, only: %i[show edit update destroy]

  # GET /employees
  # GET /employees.json
  def index
    @employees = Employee.where(status: true) # Employee.all
  end

  # GET /employees/1
  # GET /employees/1.json
  def show; end

  # GET /employees/new
  def new
    @employee = Employee.new
  end

  # GET /employees/1/edit
  def edit
    @show_btn_employee = true
  end

  # POST /employees
  # POST /employees.json
  def create
    @employee = Employee.new(format_work_days(employee_params))

    respond_to do |format|
      if @employee.save
        format.html { redirect_to @employee, notice: 'Employee was successfully created.' }
        format.json { render :show, status: :created, location: @employee }
      else
        format.html { render :new }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /employees/1
  # PATCH/PUT /employees/1.json
  def update
    respond_to do |format|
      if @employee.update(format_work_days(employee_params))
        format.html { redirect_to @employee, notice: 'Employee was successfully updated.' }
        format.json { render :show, status: :ok, location: @employee }
      else
        format.html { render :edit }
        format.json { render json: @employee.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /employees/1
  # DELETE /employees/1.json
  def destroy
    @employee = Employee.find(params[:id])
    if @employee.status
      @employee.update(status: false)
      flash[:notice] = "Successfully disabled #{@employee.name}."
      flash[:notice] = "Failed to disable #{@employee.name}."
      render action: :show
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_employee
    @employee = Employee.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def employee_params
    params.require(:employee).permit(:name, :nip, :email, :address, :phone, :position, :status, :enter_time, :departure_time, work_days: {})
  end

  def format_work_days(parameters)
    parameters[:work_days] = parameters[:work_days].keys || []
    parameters
  end
end

clock/app/views/employees/_form.html.erb
<% if employee.errors.any? %>
<div class="error">
  <div class="alert alert-danger alert-dismissible" id="Errors">
    <button type="button" class="close">&times;</button>
    <strong>Danger!</strong> 
    <div id="error_explanation">
      <h2><%= pluralize(employee.errors.count, "error") %> prohibited this employee from being saved:</h2>

      <ul>
        <% employee.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  
  </div>
</div>
  <% end %>

  <div class="container">
  <div class="row">
    <div class="col-sm-2">
      <div class="row">
        <div class="col-sm-12">
          <img src="https://picsum.photos/200/200" class="img-thumbnail" />
        </div>
      </div>
    </div>
    <div class="col-sm-10">
      <%= form_with(model: employee, local: true, class: "form-horizontal") do |form| %>
        
        <div class="form-group row">
          <%= form.label :id, class: "col-sm-2 col-form-label" %>
          <div class="col-sm-10">
          <%= form.text_field :id, placeholder: "Employee number", class: "form-control", disabled: true %>
          </div>
        </div>

        <%= form.hidden_field :status, value: true %>

        <div class="form-group row">
          <%= form.label :name, class: "col-sm-2 col-form-label" %>
          <div class="col-sm-10">
          <%= form.text_field :name, placeholder: "First name, Last name", class: "form-control" %>
          </div>
        </div>

        <div class="form-group row">
          <%= form.label :email, class: "col-sm-2 col-form-label" %>
          <div class="col-sm-10">
          <%= form.text_field :email, placeholder: "abc@mail.com", class: "form-control" %>
          </div>
        </div>

        <div class="form-group row">
          <%= form.label :position, class: "col-sm-2 col-form-label" %>
          <div class="col-sm-10">
          <%= form.text_field :position, placeholder: "CEO", class: "form-control" %>
          </div>
        </div>

        <div class="form-group row">
          <%= form.label :phone, class: "col-sm-2 col-form-label" %>
          <div class="col-sm-10">
          <%= form.text_field :phone, placeholder: "+52 (312) 000 0000", class: "form-control" %>
          </div>
        </div>

        <div class="form-group row">
          <%= form.label :address, class: "col-sm-2 col-form-label" %>
          <div class="col-sm-10">
          <%= form.text_field :address, placeholder: "Address Name # 101, Colima", class: "form-control" %>
          </div>
        </div>

        <div class="form-group row">
          <%= form.label :nip, class: "col-sm-2 col-form-label" %>
          <div class="col-sm-10">
          <%= form.text_field :nip, placeholder: "1234", class: "form-control" %>
          </div>
        </div>

        <div class="form-group row">
          <%= form.label :work_days, class: "col-sm-2 col-form-label" %>
          <div class="col-sm-10 row">
          <% ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'].each do |work_day| -%>
            <%= check_box_tag "employee[work_days][#{work_day}]", work_day, @employee.work_days&.any?(work_day), class: "col-sm-2 col-form-label", checked: true  %>
            <%= label_tag "employee[work_days][#{work_day}]", work_day, :class => "col-sm-2 col-form-label"  %>
          <% end -%>    
          </div>
        </div>

        <div class="form-group row">
          <%= form.label "Work  hours", class: "col-sm-2 col-form-label" %>
          <div class="col-sm-10">
          <%= form.time_select :enter_time %> &nbsp; to &nbsp; <%= form.time_select :departure_time %>
          </div>
        </div>

        <div class="form-group row">
          <div class="col-sm-10 offset-sm-2">
          <% if @show_btn_employee %>
            <%= link_to 'Destroy', employee, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger float-right' %>
          <% end %>
            <%= form.submit class: 'btn btn-primary float-right', data: { confirm: 'Do you want to confirm this action?' } %>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

clock/app/views/employees/edit.html.erb
<h1>Editing Employee</h1>

<%= render 'form', employee: @employee %>

<%= link_to 'Show', @employee %> |
<%= link_to 'Back', employees_path %>

clock/app/views/employees/index.html.erb
<div class="container">
  <div class="row">
      <% @employees.each do |employee| %>
        <div class="col-md-4">
          <div class="card mb-4 shadow-sm">
          <img src="https://picsum.photos/200/200" class="img-thumbnail" />
            <div class="card-body">
              <p class="card-text">
                <p><strong>Name:</strong> <%= employee.name %></p>
                <p><strong>Employee number:</strong> <%= employee.id %></p>
              </p>
              <div class="d-flex justify-content-between align-items-center">
                <%= link_to 'Show', edit_employee_path(employee), class: 'btn btn-primary btn-lg btn-block' %>
              </div>
            </div>
          </div>
        </div>
      <% end %>
  </div>
</div>

clock/app/views/employees/new.html.erb
<h1>New Employee</h1>

<%= render 'form', employee: @employee %>

<%= link_to 'Back', employees_path %>

clock/app/views/employees/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @employee.name %>
</p>

<p>
  <strong>Nip:</strong>
  <%= @employee.nip %>
</p>

<p>
  <strong>Address:</strong>
  <%= @employee.address %>
</p>

<p>
  <strong>Status:</strong>
  <%= @employee.status %>
</p>

<p>
  <strong>Work days:</strong>
  <%= @employee.work_days %>
</p>

<p>
  <strong>Enter time:</strong>
  <%= @employee.enter_time %>
</p>

<p>
  <strong>Departure time:</strong>
  <%= @employee.departure_time %>
</p>

<%= link_to 'Edit', edit_employee_path(@employee) %> |
<%= link_to 'Back', employees_path %>